In [1]:

# IMPORTANT: RUN THIS CELL IN ORDER TO IMPORT YOUR KAGGLE DATASETS
# TO THE CORRECT LOCATION (/kaggle/input) IN YOUR NOTEBOOK,
# THEN FEEL FREE TO DELETE CELL.

import os
import sys
from tempfile import NamedTemporaryFile
from urllib.request import urlopen
from urllib.parse import unquote
from urllib.error import HTTPError
from zipfile import ZipFile

CHUNK_SIZE = 40960 
DATASET_MAPPING = 'quora-question-pairs:https%3A%2F%2Fstorage.googleapis.com%2Fkaggle-competitions-data%2Fkaggle-v2%2F6277%2F323734%2Fbundle%2Farchive.zip%3FX-Goog-Algorithm%3DGOOG4-RSA-SHA256%26X-Goog-Credential%3Dgcp-kaggle-com%2540kaggle-161607.iam.gserviceaccount.com%252F20201113%252Fauto%252Fstorage%252Fgoog4_request%26X-Goog-Date%3D20201113T095322Z%26X-Goog-Expires%3D259199%26X-Goog-SignedHeaders%3Dhost%26X-Goog-Signature%3D941e65fcc557bb6027dc6bcc15001755b9c4b7ede598ece2b0eea7fccfeed46d44a723b4a169962e060eb78dbcebf5fc4e2362d68e3e3c95576365e1f1a410f788d010584f6108af6aad80ffeabbcf53f10ea002f1e551723429557b5ef34ec3ad60054f332316a54a6dda2e658707ef22c6f118a0243cf626dd4330edc90e5edccd6db4edf09f7f7d9f4db546b3e9b63c832604aff9c4506699dd5603760470f215484537d530c7bf47e98f9a98cab9864b7c1536925909e8f7bdb1f83fb5926318ef855afbc841c4aead5c0fe015660b36b15688124dde89f48cc0195723f5c6b63b3318c38da57406dcca43a461f0cc2ecfc89344ed1097269123a8aa0f8b'
KAGGLE_INPUT_PATH='/home/kaggle/input'
KAGGLE_INPUT_SYMLINK='/kaggle'

!mkdir -p -- $KAGGLE_INPUT_PATH
!chmod 777 $KAGGLE_INPUT_PATH
!ln -sfn $KAGGLE_INPUT_PATH ../
!mkdir -p -- $KAGGLE_INPUT_SYMLINK
!ln -sfn $KAGGLE_INPUT_PATH $KAGGLE_INPUT_SYMLINK

for dataset_mapping in DATASET_MAPPING.split(','):
    directory, download_url_encoded = dataset_mapping.split(':')
    download_url = unquote(download_url_encoded)
    destination_path = os.path.join(KAGGLE_INPUT_PATH, directory)
    try:
        with urlopen(download_url) as zipfileres, NamedTemporaryFile() as tfile:
            total_length = zipfileres.headers['content-length']
            print(f'Downloading {directory}, {total_length} bytes zipped')
            dl = 0
            data = zipfileres.read(CHUNK_SIZE)
            while len(data) > 0:
                dl += len(data)
                tfile.write(data)
                done = int(50 * dl / int(total_length))
                sys.stdout.write(f"\r[{'=' * done}{' ' * (50-done)}] {dl} bytes downloaded")
                sys.stdout.flush()
                data = zipfileres.read(CHUNK_SIZE)
            print(f'\nUnzipping {directory}')
            with ZipFile(tfile) as zfile:
                zfile.extractall(destination_path)
    except HTTPError as e:
        print(f'Failed to load (likely expired) {download_url} to path {destination_path}')
        continue
    except OSError as e:
        print(f'Failed to load {download_url} to path {destination_path}')
        continue
print('Dataset import complete.')

ln: ../input: cannot overwrite directory
Failed to load (likely expired) https://storage.googleapis.com/kaggle-competitions-data/kaggle-v2/6277/323734/bundle/archive.zip?X-Goog-Algorithm=GOOG4-RSA-SHA256&X-Goog-Credential=gcp-kaggle-com%40kaggle-161607.iam.gserviceaccount.com%2F20201113%2Fauto%2Fstorage%2Fgoog4_request&X-Goog-Date=20201113T095322Z&X-Goog-Expires=259199&X-Goog-SignedHeaders=host&X-Goog-Signature=941e65fcc557bb6027dc6bcc15001755b9c4b7ede598ece2b0eea7fccfeed46d44a723b4a169962e060eb78dbcebf5fc4e2362d68e3e3c95576365e1f1a410f788d010584f6108af6aad80ffeabbcf53f10ea002f1e551723429557b5ef34ec3ad60054f332316a54a6dda2e658707ef22c6f118a0243cf626dd4330edc90e5edccd6db4edf09f7f7d9f4db546b3e9b63c832604aff9c4506699dd5603760470f215484537d530c7bf47e98f9a98cab9864b7c1536925909e8f7bdb1f83fb5926318ef855afbc841c4aead5c0fe015660b36b15688124dde89f48cc0195723f5c6b63b3318c38da57406dcca43a461f0cc2ecfc89344ed1097269123a8aa0f8b to path /home/kaggle/input/quora-question-pairs
Dataset import complete.

In [2]:
# This Python 3 environment comes with many helpful analytics libraries installed
# It is defined by the kaggle/python Docker image: https://github.com/kaggle/docker-python
# For example, here's several helpful packages to load

import numpy # linear algebra
import pandas # data processing, CSV file I/O (e.g. pd.read_csv)

# Input data files are available in the read-only "../input/" directory
# For example, running this (by clicking run or pressing Shift+Enter) will list all files under the input directory

import os
for dirname, _, filenames in os.walk('/kaggle/input'):
    for filename in filenames:
        print(os.path.join(dirname, filename))

# You can write up to 20GB to the current directory (/kaggle/working/) that gets preserved as output when you create a version using "Save & Run All" 
# You can also write temporary files to /kaggle/temp/, but they won't be saved outside of the current session

/kaggle/input/quora-question-pairs/test.csv.zip
/kaggle/input/quora-question-pairs/sample_submission.csv.zip
/kaggle/input/quora-question-pairs/train.csv.zip
/kaggle/input/quora-question-pairs/test.csv

In [3]:
CURRENT_LOCAL_PATH='/kaggle/input/quora-question-pairs/'

In [4]:
! apt-get update -qq

In [5]:
! apt-get install -y openjdk-8-jdk-headless -qq

In [6]:
os.environ["JAVA_HOME"] = "/usr/lib/jvm/java-8-openjdk-amd64"
os.environ["PATH"] = os.environ["JAVA_HOME"] + "/bin:" + os.environ["PATH"]

In [7]:
! pip install nlu

Requirement already satisfied: nlu in /opt/conda/lib/python3.7/site-packages (1.0.2)
Requirement already satisfied: pyarrow>=0.16.0 in /opt/conda/lib/python3.7/site-packages (from nlu) (0.16.0)
Requirement already satisfied: spark-nlp<2.7,>=2.6.2 in /opt/conda/lib/python3.7/site-packages (from nlu) (2.6.3)
Requirement already satisfied: numpy in /opt/conda/lib/python3.7/site-packages (from nlu) (1.18.5)
Requirement already satisfied: pandas in /opt/conda/lib/python3.7/site-packages (from nlu) (1.1.3)
Requirement already satisfied: pyspark<2.5,>=2.4.0 in /opt/conda/lib/python3.7/site-packages (from nlu) (2.4.7)
Requirement already satisfied: dataclasses in /opt/conda/lib/python3.7/site-packages (from nlu) (0.6)
Requirement already satisfied: six>=1.0.0 in /opt/conda/lib/python3.7/site-packages (from pyarrow>=0.16.0->nlu) (1.14.0)
Requirement already satisfied: python-dateutil>=2.7.3 in /opt/conda/lib/python3.7/site-packages (from pandas->nlu) (2.8.1)
Requirement already satisfied: pytz>=2017.2 in /opt/conda/lib/python3.7/site-packages (from pandas->nlu) (2019.3)
Requirement already satisfied: py4j==0.10.7 in /opt/conda/lib/python3.7/site-packages (from pyspark<2.5,>=2.4.0->nlu) (0.10.7)

# use this to load the proper model model: 6 or 50  kinds of questions

In [8]:
import nlu
nlu_questions_50 = nlu.load('en.classify.questions')
nlu_questions_6 = nlu.load('classify.trec6.use')

classifierdl_use_trec50 download started this may take some time.
Approximate size to download 21.2 MB
[OK!]
tfhub_use download started this may take some time.
Approximate size to download 923.7 MB
[OK!]
classifierdl_use_trec6 download started this may take some time.
Approximate size to download 21.4 MB
[OK!]
tfhub_use download started this may take some time.
Approximate size to download 923.7 MB
[OK!]

In [9]:
import tqdm
from tqdm import tqdm_pandas
from tqdm.autonotebook  import tqdm
import gc
gc.disable()
gc.collect()


BLOCKSIZE=100000

def fake(df,num_block,first_row,block_size,tag):
    print(num_block,first_row,block_size,df.shape)
    return df

# model with 6 questions
def rename_question_kinds(df,model,tag):
    if model==6:
        df = df.drop(['sentence_embeddings','document','trec6','trec6_sentence_confidence'],axis=1)
        old_start = 'trec6_'
    else:
        df = df.drop(['questions_sentence_confidence','sentence_embeddings','document','questions'],axis=1)
        old_start =  'questions_'
    new_names= dict()
    for c in df.columns:
        if 'confidence' in c:
          new_names[c]=tag+'_'+c.replace('questions_ ','')
    df.rename(columns=new_names,inplace=True)
    return df

# df must be a dataframe with only one column named 'text'
def find_questions_types(df,num_block,first_row,block_size,model,tag):
    if model==6:
      return rename_question_kinds(nlu_questions_6.predict(df,metadata=True,output_level='document'),model,tag)
    else:
      return rename_question_kinds(nlu_questions_50.predict(df,metadata=True,output_level='document'),model,tag)
            
def by_blocks(df,block_size,func,model,tag):
    nb_blocks = int(len(df)/block_size)
    last_size = len(df) % block_size
    res = pandas.DataFrame()
    print('nb_blocks %d block_size %d last_size %d' % (nb_blocks,block_size,last_size))
    assert (nb_blocks*block_size+last_size)==len(df)
    current_row = 0
    for i in tqdm(range(nb_blocks)):
        block = df[current_row:(current_row+block_size)]
        tmp = func(block,i,current_row,block_size,model,tag)
        assert(len(tmp)==block_size), 'bad size of result block'
        res = res.append(tmp,ignore_index=False)
        print('size of result block is %d' % len(res))
        current_row += block_size
        gc.collect()
    if last_size >0:
        block = df[current_row:(current_row+last_size)]
        tmp = func(block,nb_blocks,current_row,last_size,model,tag)
        assert(len(tmp)==last_size), 'bad size of last result block'
        res = res.append(tmp,ignore_index=False)
        print('size of result block is %d' % len(res))
        gc.collect()
    return res

def compute_all_questions_question1(dataframe,dataset_name):
    tag = '1_6'
    print('6 questions type')
    res=by_blocks(dataframe,BLOCKSIZE,find_questions_types,6,tag)
    display(res.head())
    display(res.describe())
    res.to_pickle('./'+dataset_name+'questions_question_'+tag+'.pkl')
    res.to_csv('./'+dataset_name+'questions_question_'+tag+'.csv')
    assert len(res) == len(dataframe), "size of result for 6 is not OK"

    tag = '1_50'
    print('50 questions type')
    res=by_blocks(dataframe,BLOCKSIZE,find_questions_types,50,tag)
    display(res.head())
    display(res.describe())
    res.to_pickle('./'+dataset_name+'questions_question_'+tag+'.pkl')
    res.to_csv('./'+dataset_name+'questions_question_'+tag+'.csv')
    assert len(res) == len(dataframe), "size of result for 50 is not OK"

def compute_all_questions_question2(dataframe,dataset_name):
    tag = '2_6'
    print('6 questions type %s for %s ' % (tag,dataset_name))
    res=by_blocks(dataframe,BLOCKSIZE,find_questions_types,6,tag)
    display(res.describe())
    res.to_pickle('./'+dataset_name+'questions_question_'+tag+'.pkl')
    res.to_csv('./'+dataset_name+'questions_question_'+tag+'.csv')
    assert len(res) == len(dataframe), "size of result for 6 is not OK"

    tag = '2_50'
    
    print('50 questions type %s for %s ' % (tag,dataset_name))
    res=by_blocks(dataframe,BLOCKSIZE,find_questions_types,50,tag)
    display(res.describe())
    res.to_pickle('./'+dataset_name+'questions_question_'+tag+'.pkl')
    res.to_csv('./'+dataset_name+'questions_question_'+tag+'.csv')
    assert len(res) == len(dataframe), "size of result for 50 is not OK"
    
UNITARY_TEST=True
# rehearsal
if UNITARY_TEST:
    train_dataframe = pandas.read_csv(CURRENT_LOCAL_PATH+'train.csv.zip',error_bad_lines=True,warn_bad_lines=True)
    small_train=train_dataframe.sample(10,random_state=42)
    small_train.rename(columns={'question1':'text'},inplace=True)
    small_train=small_train.drop(['question2',"id","qid1","qid2","is_duplicate"],axis=1)
    small_train.fillna('?',inplace=True)
    print(small_train.shape)
    compute_all_questions_question1(small_train,'small_train')
    compute_all_questions_question2(small_train,'small_train')

(10, 1)
6 questions type
nb_blocks 0 block_size 100000 last_size 10

HBox(children=(FloatProgress(value=1.0, bar_style='info', max=1.0), HTML(value='')))

size of result block is 10

,1_6_trec6_ ABBR_confidence,1_6_trec6_ HUM_confidence,1_6_trec6_ NUM_confidence,1_6_trec6_ ENTY_confidence,1_6_trec6_ DESC_confidence,1_6_trec6_ LOC_confidence
origin_index,,,,,,
8067,1.6906414E-10,7.043194E-11,3.349789E-8,7.791751E-7,0.99999905,1.254212E-7
368101,1.4315921E-13,3.6691115E-5,7.574819E-13,0.9999604,1.100334E-8,2.9058115E-6
70497,5.304409E-12,3.7957852E-6,4.9903075E-8,0.9999958,4.0147324E-7,9.064922E-11
226567,2.3629159E-9,8.459071E-9,6.745665E-7,1.3178503E-5,0.9999862,1.7516246E-9
73186,3.2993032E-8,8.3458684E-7,0.9985222,1.8907886E-5,2.231484E-4,0.0012348648

,1_6_trec6_ ABBR_confidence,1_6_trec6_ HUM_confidence,1_6_trec6_ NUM_confidence,1_6_trec6_ ENTY_confidence,1_6_trec6_ DESC_confidence,1_6_trec6_ LOC_confidence
count,10,10,10,10,10,10
unique,9,9,9,9,9,9
top,2.3629159E-9,8.459071E-9,6.745665E-7,1.3178503E-5,0.9999862,1.7516246E-9
freq,2,2,2,2,2,2

50 questions type
nb_blocks 0 block_size 100000 last_size 10

HBox(children=(FloatProgress(value=1.0, bar_style='info', max=1.0), HTML(value='')))

size of result block is 10

,1_50_ENTY_other_confidence,1_50_LOC_mount_confidence,1_50_NUM_ord_confidence,1_50_NUM_money_confidence,1_50_ENTY_techmeth_confidence,1_50_ENTY_product_confidence,1_50_NUM_temp_confidence,1_50_NUM_period_confidence,1_50_ENTY_religion_confidence,1_50_HUM_title_confidence,...,1_50_HUM_gr_confidence,1_50_ABBR_exp_confidence,1_50_ENTY_sport_confidence,1_50_ENTY_lang_confidence,1_50_LOC_city_confidence,1_50_ABBR_abb_confidence,1_50_ENTY_animal_confidence,1_50_DESC_def_confidence,1_50_LOC_other_confidence,1_50_LOC_country_confidence
origin_index,,,,,,,,,,,,,,,,,,,,,
8067,2.015917E-18,2.9720082E-27,1.6930101E-29,1.10442625E-23,6.4277225E-25,4.846992E-27,5.667094E-28,4.943256E-25,3.6368013E-26,2.9136003E-28,...,3.5369693E-23,1.4201224E-27,2.7133596E-29,4.220785E-29,3.18404E-26,2.381897E-28,2.4329213E-26,6.3362604E-17,2.1751209E-21,2.4169194E-25
368101,0.013039745,3.4403447E-19,2.33227E-20,8.456879E-15,2.9029947E-16,9.474704E-19,3.7925278E-20,3.9595746E-17,5.821724E-17,5.630197E-19,...,4.9937546E-14,4.1161107E-18,6.186508E-20,4.829836E-19,1.5886108E-17,5.643698E-20,6.918692E-17,2.1236852E-9,0.92955023,2.2474414E-15
70497,0.018172478,1.0601772E-21,7.6474104E-25,3.434696E-19,2.9654467E-20,5.5732913E-21,2.0250592E-22,1.5285039E-19,3.4750205E-21,2.2108783E-23,...,3.1959018E-18,3.4573272E-22,8.052517E-23,2.6729712E-22,1.1689118E-21,2.2351994E-23,2.8643465E-21,3.3617112E-22,1.7977316E-17,1.7357407E-17
226567,5.448056E-8,1.8033229E-17,5.814997E-20,5.023707E-15,7.6718117E-17,1.2139217E-17,2.6236879E-18,6.7013107E-16,3.7825682E-17,7.441726E-19,...,1.2467089E-14,1.9732391E-18,7.660191E-20,3.0210314E-19,2.930389E-17,1.2024955E-18,2.350613E-17,5.4838106E-6,4.8990794E-17,1.1463241E-15
73186,4.6349844E-4,5.213016E-18,1.5582175E-20,1.3145538E-15,4.2841712E-17,7.694615E-18,9.820632E-19,4.9709987E-16,5.6923876E-17,6.3579454E-19,...,2.591358E-14,1.8580915E-18,4.0391346E-20,1.5779579E-19,9.364877E-18,5.7678803E-19,4.4693164E-18,3.9212737E-6,1.8918598E-8,2.4164052E-15

,1_50_ENTY_other_confidence,1_50_LOC_mount_confidence,1_50_NUM_ord_confidence,1_50_NUM_money_confidence,1_50_ENTY_techmeth_confidence,1_50_ENTY_product_confidence,1_50_NUM_temp_confidence,1_50_NUM_period_confidence,1_50_ENTY_religion_confidence,1_50_HUM_title_confidence,...,1_50_HUM_gr_confidence,1_50_ABBR_exp_confidence,1_50_ENTY_sport_confidence,1_50_ENTY_lang_confidence,1_50_LOC_city_confidence,1_50_ABBR_abb_confidence,1_50_ENTY_animal_confidence,1_50_DESC_def_confidence,1_50_LOC_other_confidence,1_50_LOC_country_confidence
count,10,10,10,10,10,10,10,10,10,10,...,10,10,10,10,10,10,10,10,10,10
unique,9,9,9,9,9,9,9,9,9,9,...,9,9,9,9,9,9,9,9,9,9
top,5.448056E-8,1.8033229E-17,5.814997E-20,5.023707E-15,7.6718117E-17,1.2139217E-17,2.6236879E-18,6.7013107E-16,3.7825682E-17,7.441726E-19,...,1.2467089E-14,1.9732391E-18,7.660191E-20,3.0210314E-19,2.930389E-17,1.2024955E-18,2.350613E-17,5.4838106E-6,4.8990794E-17,1.1463241E-15
freq,2,2,2,2,2,2,2,2,2,2,...,2,2,2,2,2,2,2,2,2,2

6 questions type 2_6 for small_train
nb_blocks 0 block_size 100000 last_size 10

HBox(children=(FloatProgress(value=1.0, bar_style='info', max=1.0), HTML(value='')))

size of result block is 10

,2_6_trec6_ ABBR_confidence,2_6_trec6_ HUM_confidence,2_6_trec6_ NUM_confidence,2_6_trec6_ ENTY_confidence,2_6_trec6_ DESC_confidence,2_6_trec6_ LOC_confidence
count,10,10,10,10,10,10
unique,9,9,9,9,9,9
top,2.3629159E-9,8.459071E-9,6.745665E-7,1.3178503E-5,0.9999862,1.7516246E-9
freq,2,2,2,2,2,2

50 questions type 2_50 for small_train
nb_blocks 0 block_size 100000 last_size 10

HBox(children=(FloatProgress(value=1.0, bar_style='info', max=1.0), HTML(value='')))

size of result block is 10

,2_50_ENTY_other_confidence,2_50_LOC_mount_confidence,2_50_NUM_ord_confidence,2_50_NUM_money_confidence,2_50_ENTY_techmeth_confidence,2_50_ENTY_product_confidence,2_50_NUM_temp_confidence,2_50_NUM_period_confidence,2_50_ENTY_religion_confidence,2_50_HUM_title_confidence,...,2_50_HUM_gr_confidence,2_50_ABBR_exp_confidence,2_50_ENTY_sport_confidence,2_50_ENTY_lang_confidence,2_50_LOC_city_confidence,2_50_ABBR_abb_confidence,2_50_ENTY_animal_confidence,2_50_DESC_def_confidence,2_50_LOC_other_confidence,2_50_LOC_country_confidence
count,10,10,10,10,10,10,10,10,10,10,...,10,10,10,10,10,10,10,10,10,10
unique,9,9,9,9,9,9,9,9,9,9,...,9,9,9,9,9,9,9,9,9,9
top,5.448056E-8,1.8033229E-17,5.814997E-20,5.023707E-15,7.6718117E-17,1.2139217E-17,2.6236879E-18,6.7013107E-16,3.7825682E-17,7.441726E-19,...,1.2467089E-14,1.9732391E-18,7.660191E-20,3.0210314E-19,2.930389E-17,1.2024955E-18,2.350613E-17,5.4838106E-6,4.8990794E-17,1.1463241E-15
freq,2,2,2,2,2,2,2,2,2,2,...,2,2,2,2,2,2,2,2,2,2

In [ ]:
gc.enable()
gc.collect()
gc.disable()
training_dataframe = pandas.read_pickle('../PandasStore/clean_training.pkl')
training_dataframe.rename(columns={'question1':'text'},inplace=True)
training_dataframe=training_dataframe.drop(['question2',"id","qid1","qid2","is_duplicate"],axis=1)
training_dataframe.fillna('?',inplace=True)
training_dataframe = training_dataframe.replace('','?')
display(training_dataframe.head())
training_dataframe.describe()
compute_all_questions_question1(training_dataframe,'training')

In [ ]:
gc.enable()
gc.collect()
gc.disable()
training_dataframe = pandas.read_pickle('../PandasStore/clean_training.pkl')
training_dataframe.rename(columns={'question2':'text'},inplace=True)
training_dataframe=training_dataframe.drop(['question1',"id","qid1","qid2","is_duplicate"],axis=1)
training_dataframe.fillna('?',inplace=True)
training_dataframe = training_dataframe.replace('','?')
display(training_dataframe.head())
training_dataframe.describe()
compute_all_questions_question2(training_dataframe,'training')

In [ ]:
gc.enable()
gc.collect()
gc.disable()
challenge_dataframe = pandas.read_pickle('../PandasStore/clean_challenge.pkl')
challenge_dataframe.rename(columns={'question1':'text'},inplace=True)
challenge_dataframe=challenge_dataframe.drop(['question2',"test_id"],axis=1)
challenge_dataframe.fillna('?',inplace=True)
challenge_dataframe = challenge_dataframe.replace('','?')
display(challenge_dataframe.head())
challenge_dataframe.describe()
    
compute_all_questions_question1(challenge_dataframe,'challenge')

In [10]:
gc.enable()
gc.collect()
gc.disable()
challenge_dataframe = pandas.read_pickle('../PandasStore/clean_challenge.pkl')
challenge_dataframe.rename(columns={'question2':'text'},inplace=True)
challenge_dataframe=challenge_dataframe.drop(['question1',"test_id"],axis=1)
challenge_dataframe.fillna('?',inplace=True)
challenge_dataframe = challenge_dataframe.replace('','?')
display(challenge_dataframe.head())
challenge_dataframe.describe()
    
compute_all_questions_question2(challenge_dataframe,'challenge')

                                                text
0  Why did Microsoft choose core m3 and not core ...
1        How much cost does hair transplant require?
2                      What you send money to China?
3                                  What foods fibre?
4                     How their can I start reading?

6 questions type 2_6 for challenge
nb_blocks 23 block_size 100000 last_size 45796

HBox(children=(FloatProgress(value=0.0, max=23.0), HTML(value='')))

size of result block is 100000
size of result block is 200000
size of result block is 300000
size of result block is 400000
size of result block is 500000
size of result block is 600000
size of result block is 700000
size of result block is 800000
size of result block is 900000
size of result block is 1000000
size of result block is 1100000
size of result block is 1200000
size of result block is 1300000
size of result block is 1400000
size of result block is 1500000
size of result block is 1600000
size of result block is 1700000
size of result block is 1800000
size of result block is 1900000
size of result block is 2000000
size of result block is 2100000
size of result block is 2200000
size of result block is 2300000

size of result block is 2345796

,2_6_trec6_ ABBR_confidence,2_6_trec6_ HUM_confidence,2_6_trec6_ NUM_confidence,2_6_trec6_ ENTY_confidence,2_6_trec6_ DESC_confidence,2_6_trec6_ LOC_confidence
count,2345796,2345796,2345796,2345796,2345796,2345796
unique,2211125,2159839,2121264,2041976,1240620,2183357
top,4.6002082E-12,1.0,1.0,1.0,1.0,1.0
freq,1359,15429,25496,11050,54965,2173

50 questions type 2_50 for challenge
nb_blocks 23 block_size 100000 last_size 45796

HBox(children=(FloatProgress(value=0.0, max=23.0), HTML(value='')))

size of result block is 100000
size of result block is 200000
size of result block is 300000
size of result block is 400000
size of result block is 500000
size of result block is 600000
size of result block is 700000
size of result block is 800000
size of result block is 900000
size of result block is 1000000
size of result block is 1100000
size of result block is 1200000
size of result block is 1300000
size of result block is 1400000
size of result block is 1500000
size of result block is 1600000
size of result block is 1700000
size of result block is 1800000
size of result block is 1900000
size of result block is 2000000
size of result block is 2100000
size of result block is 2200000
size of result block is 2300000

size of result block is 2345796

,2_50_ENTY_other_confidence,2_50_LOC_mount_confidence,2_50_NUM_ord_confidence,2_50_NUM_money_confidence,2_50_ENTY_techmeth_confidence,2_50_ENTY_product_confidence,2_50_NUM_temp_confidence,2_50_NUM_period_confidence,2_50_ENTY_religion_confidence,2_50_HUM_title_confidence,...,2_50_HUM_gr_confidence,2_50_ABBR_exp_confidence,2_50_ENTY_sport_confidence,2_50_ENTY_lang_confidence,2_50_LOC_city_confidence,2_50_ABBR_abb_confidence,2_50_ENTY_animal_confidence,2_50_DESC_def_confidence,2_50_LOC_other_confidence,2_50_LOC_country_confidence
count,2345796,2345796,2345796,2345796,2345796,2345796,2345796,2345796,2345796,2345796,...,2345796,2345796,2345796,2345796,2345796,2345796,2345796,2345796,2345796,2345796
unique,2191092,2181801,2152431,2201281,2192779,2182073,2170858,2192915,2188023,2171714,...,2203437,2178597,2164464,2174189,2185982,2167221,2189997,2119892,2158440,2204885
top,3.8217546E-15,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,...,0.0,0.0,0.0,0.0,0.0,0.0,0.0,1.0,1.0,0.0
freq,1359,33993,66253,14164,23555,34246,46598,23335,28047,44577,...,11141,37563,54737,42327,29881,49636,25185,31290,23533,9054